### PR TITLE
Milestone 5: Click Event

### PR DESCRIPTION
**Pull request by rukundoeric**
## What does this do? 
*  Calculator
## Description of Task to be completed? 
*  In this milestone I Added a click event on all buttons.
## How should this be manually tested? 
NOTE: Make sure you have Node.js and npm or yarn installed on your PC.
- Clone this repo: `git clone https://github.com/rukundoeric/calculator.git`
- Navigate into the project directory: `cd calculator`
- Install all packages: `yarn install or npm install`
- Start the app: `yarn start or npm start`
- or just open Live-Demo [HERE](https://calculator-2v.herokuapp.com/)

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @rukundoeric :wave: 

Your calculator is almost ready. 

* The percentage operation isn't working properly; it should divide the number by 100 when it is used.

[**Optional**] It would be nice if after pressing the equal sign to get the total, if one starts another evaluation without using the **a/c button** to set total to zero(0), that total and next should be set to zero, just like an everyday calculator.

#### Importantly, fix the percentage issue, then submit another form for code review.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Comment by rukundoeric** [comment]
Hey @uche-inyama, That is not a percentage operator it is modulus(mod). find more about it here https://www.mathsisfun.com/definitions/modulo-operation.html, so with all due respect there nothing to change about it. It working exactly how it supposed to be working.

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Changes required❌.

This is in response to the issue raised earlier, let revisit the recommendations made in the previous review.
That requirement has its root in milestone 4, it states:
" _`operate` switches `operation` and uses `plus`, `minus`, `times`, `div` and `modifier` (turning the number into a percentage based number, `e.g. 95 % == .95`) functions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png))"
Let us look at the example `95%=== 0.95` clearly the modulus does not come in here, plus modulus does not feature in a simple calculator.

> When you have a difficulty with a review, contact the code reviewer on slack or linkedIn or perhaps a TSE friend for clarifications. The reviewer is very unlikely to comeback to the pull request to address your difficulty. Thank you.

#### That is it, let us address the issue raised and submit a re-review👨.

#### Happy coding👨‍💻

Addo Forison

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
